### ISSUE TITLE
How do you close eww windows?

### ISSUE THREAD

**Issue by Mattio-cmd** [PanicKk/dotfiles#1]
I was browsing (and copying) your dotfiles for eww. They are amazing, but as i used the scripts for opening the dashboard, i cant close it afterwards. In my wm my kill keybind does nothing i have to run a `killall eww`.
Im just wandering, how do you close your eww widgets/windows?

**Comment by PanicKk** [comment]
> I use the same keybinds to open/close them, I have added the keybinds on my i3 `config` file, but the script works using --toggle so if the window is not open, it opens it, and if it is open, it closes it.

**Comment by Mattio-cmd** [comment]
> > I use the same keybinds to open/close them, I have added the keybinds on my i3 `config` file, but the script works using --toggle so if the window is not open, it opens it, and if it is open, it closes it.

Hmm, i see. Thanks then. Im sure ill figure it out
